NHSNLINK-386 - Validation of access token used in REST requests
lantanagroup/link pull request #113
Opened 2021-09-02 18:06 UTC by arianamihailescu

2021-09-02 23:50 UTC, seanmcilvenna requested changes

2021-09-02 23:50 UTC, seanmcilvenna commented on web/src/main/angular/app/services/auth.service.ts
> +        console.log('Your token is: ' + this.token);
Remove this console.log please

2021-09-02 23:50 UTC, seanmcilvenna commented on web/src/main/angular/app/services/auth.service.ts
> +        await this.oauthService.setupAutomaticSilentRefresh();
Did this get removed accidentally somewhere? Thought we had this already...

2021-09-03 16:10 UTC, arianamihailescu commented on web/src/main/angular/app/services/auth.service.ts
> +        console.log('Your token is: ' + this.token);
Removed

2021-09-03 16:11 UTC, arianamihailescu commented on web/src/main/angular/app/services/auth.service.ts
> +        await this.oauthService.setupAutomaticSilentRefresh();
Yes - but needed some changes around it to be sure we have the latest token.

2021-09-03 16:29 UTC, merged