Measure storage operation
lantanagroup/link pull request #345
Opened 2022-07-15 19:00 UTC by SaraMunich-Lantana

I created functionality and a unit test for MeasureStoreController.storeMeasure() to store measure bundles in the current working directory within the path specified in MeasureEvalConfig.

2022-07-15 21:05 UTC, seanmcilvenna requested changes

2022-07-15 21:05 UTC, seanmcilvenna commented on measureeval/src/main/java/com/lantanagroup/link/measureeval/controller/MeasureStoreController.java
> +    String measureContentXML = ctx.newXmlParser().encodeResourceToString(measureBundle);
Should null/empty-check the `measureBundle.getId()`, since it is used to populate the filename, and therefore required.

2022-07-15 21:05 UTC, seanmcilvenna commented on measureeval/src/main/java/com/lantanagroup/link/measureeval/controller/MeasureStoreController.java
>      System.out.println(this.config.getMeasuresPath());
Remove `System.out.println()` and replace with `logger.debug()` if appropriate.

2022-07-15 21:05 UTC, seanmcilvenna commented on measureeval/src/main/java/com/lantanagroup/link/measureeval/controller/MeasureStoreControllerTest.java
> +    MeasureEvalConfig config = new MeasureEvalConfig();
Don't necessarily need to make a change here... Just a thought/consideration:
Should unit tests write to file systems? I know best practices indicate that unit tests shouldn't write to DBs... I kinda consider file systems to be one in the same.
I wonder if there should be a mechanism to mock out the process of writing to a file so that we can assume writing to a file works in the unit test, without actually modifying the file system?
Perhaps consider creating a separate method that uses the simplified `Files` class (see https://www.baeldung.com/java-write-to-file section 8) to write/create the file and then mock that method out in the unit test to assume it succeeds?

2022-07-15 22:04 UTC, arianamihailescu commented on measureeval/src/main/java/com/lantanagroup/link/measureeval/controller/MeasureStoreController.java
> +        e.printStackTrace();
Let the IO Exception be thrown  - they will be handled in the Global exception handler.

2022-07-15 22:04 UTC, arianamihailescu commented on measureeval/src/main/java/com/lantanagroup/link/measureeval/controller/MeasureStoreController.java
> +      ex.printStackTrace();
Let the IO Exception be thrown - they will be handled in the Global exception handler.

2022-07-18 16:58 UTC, smailliwcs requested changes

2022-07-18 16:58 UTC, smailliwcs commented on measureeval/src/main/java/com/lantanagroup/link/measureeval/controller/MeasureStoreController.java
> +      BufferedWriter writer = Files.newBufferedWriter(
Would recommend "try-with-resources" here to make sure the writer gets flushed/closed.  Then you could remove the explicit call to `flush` on line 54.

https://kodejava.org/how-to-write-file-using-files-newbufferedwriter/

2022-07-19 17:32 UTC, merged