SharedService SQL Server Conversion
lantanagroup/link pull request #529
Opened 2023-06-28 20:49 UTC by MontaltoNick

Remaining items to convert SharedService.java to use SQL Server in place of Mongo.

2023-06-28 21:51 UTC, seanmcilvenna requested changes

2023-06-28 21:51 UTC, seanmcilvenna commented on core/src/main/java/com/lantanagroup/link/db/SharedService.java
> +  public ArrayList<MeasureDefinition> getMeasureDefinitions() {
Prefer to respond with the `List` interface

2023-06-28 21:51 UTC, seanmcilvenna commented on core/src/main/java/com/lantanagroup/link/db/SharedService.java
> +      cs.setNString("bundle", mapper.writeValueAsString(measureDefinition.getBundle()));
Since `bundle` represents FHIR, I suggest using the HAPI FHIR serializer/deserializer. It handles a number of things about the FHIR spec that the default serializers do not.
Example:
`FhirContextProvider.getFhirContext().newJsonParser().resourceAsString(measureDefinition.getBundle());`
and to deserialize:
`FhirContextProvider.getFhirContext().newJsonParser().parseResource(Bundle.class, jsonString);`

2023-06-28 21:51 UTC, seanmcilvenna commented on core/src/main/java/com/lantanagroup/link/db/SharedService.java
> +  public MongoClient getClient() {
Does this class need `getClient(): MongoClient` anymore?

2023-06-29 21:22 UTC, MontaltoNick commented on core/src/main/java/com/lantanagroup/link/db/SharedService.java
> +      cs.setNString("bundle", mapper.writeValueAsString(measureDefinition.getBundle()));
Okay - do I only need this here and the other serialize operations are fine?

2023-06-29 21:23 UTC, MontaltoNick commented on core/src/main/java/com/lantanagroup/link/db/SharedService.java
> +  public MongoClient getClient() {
I will double check and remove if not.

2023-06-30 17:00 UTC, MontaltoNick commented on core/src/main/java/com/lantanagroup/link/db/SharedService.java
> +  public MongoClient getClient() {
The 'public MongoClient getClient()' function is used in the TenantService (that Steven is working on. this reference might go away) and the BulkStatusService. Is the BulkStatusService something that we will be keeping around and need to adapt as well? Or will that be ripped out with the conversion?

2023-06-30 17:14 UTC, MontaltoNick commented on core/src/main/java/com/lantanagroup/link/db/SharedService.java
> +      cs.setNString("bundle", mapper.writeValueAsString(measureDefinition.getBundle()));
I converted this as requested.

2023-06-30 17:14 UTC, MontaltoNick commented on core/src/main/java/com/lantanagroup/link/db/SharedService.java
> +  public ArrayList<MeasureDefinition> getMeasureDefinitions() {
Done!

2023-07-06 14:38 UTC, MontaltoNick commented on core/src/main/java/com/lantanagroup/link/db/SharedService.java
> +  public MongoClient getClient() {
It looks like Steven deleted this in his branch - so this should be sorted out once we merge everything together.

2023-07-11 18:18 UTC, merged