LNK-1199 Patients incorrectly included in submission bundle
lantanagroup/link pull request #545
Opened 2023-08-21 20:23 UTC by seanmcilvenna

2023-08-22 16:03 UTC, smailliwcs requested changes

2023-08-22 16:03 UTC, smailliwcs commented on core/src/main/resources/logback.xml
Don't think we need this file in `core`.  Won't the one in `api` override it anyway?

2023-08-22 17:17 UTC, seanmcilvenna commented on core/src/main/java/com/lantanagroup/link/FhirBundler.java
> +
Yah, good point. I know another conversation is in the works that's questioning the value of the contained `subjectResults` List... If we didn't have that contained list, could we just look at the aggregate's MeasureReport.evaluatedResources for each referenced MeasureReport? I know we don't populate the aggregate's `MeasureReport.evaluatedResources` yet... But, that could be an alternative to the (in my opinion) useless contained List. Because we _currently_ populate a contained List, I'll revive logic for this change to base it on that, and consider changing it to use evaluatedResources if we end up removing the contained list.

2023-08-22 17:35 UTC, smailliwcs commented on core/src/main/java/com/lantanagroup/link/FhirBundler.java
> +
Hmm, I thought the objection was more to the fact that the list was contained, rather than that it was useless.  Because there's certainly a use _here_.  Not to mention ... isn't it expected that an aggregate measure report will refer to such a list?  From the R4 spec's description of the `subjectResults` element:

> This element refers to a List of subject level MeasureReport resources, one for each subject in this population.

If we still want the list, but we don't want it to be contained, we could promote it to the top level of the bundle (as we do for line-level resources), then tweak the reference as it appears in the aggregate's `subjectResults`.

2023-08-22 18:07 UTC, seanmcilvenna commented on core/src/main/resources/logback.xml
It's useful for reducing log noise in unit tests, at least. The one in core isn't used at runtime because the one in api takes precedence, I believe. But, when running unit tests in `core`, it only knows the logback configuration within `core`.

2023-08-23 21:35 UTC, seanmcilvenna commented on core/src/main/java/com/lantanagroup/link/FhirBundler.java
> +
Per discussion, re-created functionality to only look at individual measure reports that are asserted within the aggregate's contained subject-list List. See screenshot for test run that shows database has more individual patient measure reports in it than the aggregate asserts, but the logic is only using the `indMeasureReports` variable to add data to the bundle, rather than using `allIndMeasureReports`.

![image](https://github.com/lantanagroup/link/assets/5384694/01dca23e-5d8d-485c-9ac0-ed4b20833e0c)

2023-08-24 14:45 UTC, smailliwcs approved these changes

2023-08-24 14:45 UTC, smailliwcs commented on core/src/main/java/com/lantanagroup/link/FhirBundler.java
> +      }
Do we still need this check?  Won't the `subjectResults` list contain _only_ individual measure reports that are in the IP?  Though no harm in leaving it in.

2023-08-24 14:57 UTC, merged