LNK-1382: Changed metric log generation to SQL table entry generation.
lantanagroup/link pull request #560
Opened 2023-10-11 20:56 UTC by ajagann1

2023-10-13 15:11 UTC, smailliwcs requested changes
One general comment ... see partial output below.  I think the intention was for the category to be the first part of the old task name in most cases.  E.g., `query-Patient` should get split into category `query` and task name `Patient`.  Unless you got different guidance from Sean.

| category | taskName | data |
| -------- | -------- | ---- |
| report | evaluate-measure | {"count":20,"duration":104651} |
| report | evaluate-phase-INITIAL | {"count":1,"duration":26463} |
| report | evaluate-phase-SUPPLEMENTAL | {"count":1,"duration":3254} |
| report | event-CodeSystemCleanup | {"count":20,"duration":175} |
| report | event-ContainedResourceCleanup | {"count":20,"duration":1} |
| report | event-CopyLocationIdentifierToType | {"count":20,"duration":2} |
| report | event-EncounterStatusTransformer | {"count":20,"duration":0} |
| report | event-FixPeriodDates | {"count":20,"duration":80} |
| report | event-FixResourceId | {"count":20,"duration":102} |
| report | event-PatientDataResourceFilter | {"count":82,"duration":19} |
| report | query-Condition | {"count":2,"duration":1461} |
| report | query-Coverage | {"count":2,"duration":673} |
| report | query-Encounter | {"count":18,"duration":10201} |
| report | query-Location | {"count":18,"duration":6800} |
| report | query-Medication | {"count":18,"duration":10765} |
| report | query-MedicationRequest | {"count":18,"duration":18467} |
| report | query-Observation | {"count":2,"duration":8049} |
| report | query-Patient | {"count":19,"duration":13294} |
| report | query-phase-INITIAL | {"count":1,"duration":7561} |
| report | query-phase-SUPPLEMENTAL | {"count":1,"duration":13589} |
| report | query-ServiceRequest | {"count":2,"duration":7689} |
| report | query-Specimen | {"count":2,"duration":1715} |
| report | retrieve-patient-data | {"count":20,"duration":411} |
| report | store-measure-report | {"count":20,"duration":653} |
| report | store-patient-data | {"count":20,"duration":4082} |

2023-10-13 15:22 UTC, seanmcilvenna commented
Agree with @smailliwcs's comment about the intent of `category` column.

2023-10-17 16:15 UTC, ajagann1 commented on api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java
> +    this.stopwatchManager.storeMetrics(tenantService.getConfig().getId(), report.getId(), Constants.QUERY);
Done

2023-10-17 16:16 UTC, ajagann1 commented on api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java
> -    logger.info("Statistics for entire report:\n{}", this.stopwatchManager.getStatistics());
Done

2023-10-17 16:32 UTC, ajagann1 commented on api/src/main/java/com/lantanagroup/link/api/controller/ValidationController.java
> +        stopwatchManager.storeMetrics(tenantId, reportId, Constants.VALIDATION);
Refactored the code to only collect metrics when there's a direct call for validation on a stored reportID, rather than trying to determine if the Bundle being examined is a MeasureReport or not.

2023-10-17 16:34 UTC, merged