LNK-1360: Reporting metrics rest controller
lantanagroup/link pull request #565
Opened 2023-11-05 15:54 UTC by amphillipsLGC

Added a new metrics rest controller along with methods to calculate the various metrics needed for reporting.

2023-11-05 19:32 UTC, seanmcilvenna requested changes
Only some syntax complaints. Otherwise looks super solid. Going to checkout the branch later and try it out, too. Happy to merge as is though, too.

2023-11-05 19:32 UTC, seanmcilvenna commented on api/src/main/java/com/lantanagroup/link/api/controller/MetricController.java
> +  private static final String QUERY_CATEGORY = "query";
Move these to the Constants class please. These may be used by other code I suspect.

2023-11-05 19:32 UTC, seanmcilvenna commented on api/src/main/java/com/lantanagroup/link/api/controller/MetricController.java
> +  private MetricsReportResponse CalculatePeriodMetrics(String period, LocalDate end, List<Metrics> metrics) {
Java is camel case method naming..
`calculatePeriodMetrics()`

2023-11-06 13:19 UTC, amphillipsLGC commented on api/src/main/java/com/lantanagroup/link/api/controller/MetricController.java
> +  private MetricsReportResponse CalculatePeriodMetrics(String period, LocalDate end, List<Metrics> metrics) {
Eww but fixed haha.

2023-11-06 16:23 UTC, seanmcilvenna approved these changes

2023-11-06 16:24 UTC, merged