LNK-1816 - configurable to apply db schema changes or not
lantanagroup/link pull request #594
Opened 2023-12-14 21:19 UTC by seanmcilvenna

2023-12-18 17:39 UTC, smailliwcs requested changes

2023-12-18 17:39 UTC, smailliwcs commented on api/src/main/java/com/lantanagroup/link/api/ApiInit.java
> +      return;
Was this early return intentional?  Wouldn't we still want to perform the remaining checks in this method?

2023-12-21 00:31 UTC, seanmcilvenna commented on api/src/main/java/com/lantanagroup/link/api/ApiInit.java
> +      return;
Removed the `return`. Good catch. Not sure what I was thinking

2023-12-21 14:55 UTC, smailliwcs approved these changes

2023-12-21 16:49 UTC, merged