LNK-1825
lantanagroup/link pull request #674
Opened 2024-01-25 21:09 UTC by MontaltoNick

Add Category handling to metrics output logging.

2024-01-26 16:59 UTC, smailliwcs requested changes

2024-01-26 16:59 UTC, smailliwcs commented on core/src/main/java/com/lantanagroup/link/time/StopwatchManager.java
> +    var categoryWidth = maxCategory.getKey().substring(maxCategory.getKey().indexOf(":") + 1).length() + 5;
Not following this logic.  The lambda supplied to `Stream.max` is a `Comparator`:

https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/stream/Stream.html#max(java.util.Comparator)

Don't think that's what you want here.  Would recommend mapping to an `IntStream` first and *then* calling `max`.  Should also update the calculation of `taskWidth` above.  Something like this:

```java
int taskWidth = durationsByTask.keySet().stream()
        .mapToInt(key -> key.indexOf(":"))
        .max()
        .orElse(0);
taskWidth = Integer.max(taskWidth, TASK_WIDTH_MIN);
int categoryWidth = durationsByTask.keySet().stream()
        .mapToInt(key -> key.length() - key.indexOf(":") - 1)
        .max()
        .orElse(0);
categoryWidth = Integer.max(categoryWidth, CATEGORY_WIDTH_MIN);
```

Note that there's no `TASK_WIDTH_MIN` currently defined, but since you added one for the category, we should probably do the same for task.

2024-01-26 16:59 UTC, smailliwcs commented on core/src/main/java/com/lantanagroup/link/time/StopwatchManager.java
> +    }
Remove if using the `Integer.max` call suggested above.

2024-01-26 18:14 UTC, MontaltoNick commented on core/src/main/java/com/lantanagroup/link/time/StopwatchManager.java
> +    var categoryWidth = maxCategory.getKey().substring(maxCategory.getKey().indexOf(":") + 1).length() + 5;
My goal was to get the category with the largest value to use as the column width. I wasn't aware of the mapToInt functionality in Java - that is more concise compared to what I was doing.

2024-01-29 18:48 UTC, smailliwcs approved these changes

2024-01-29 19:58 UTC, merged