LNK-1871: Some refactors to the FileSystemSender. Also, updates to an…
lantanagroup/link pull request #716
Opened 2024-03-07 21:56 UTC by ajagann1

…notate validation results with what file each issue listed in the results comes from when the not a Bundle flag is set in the sender configuration and saves said results to the same location as the rest of the bundle files.

2024-03-08 06:00 UTC, seanmcilvenna approved these changes
Consider re-formatting/indenting the file as a whole... Noticed a couple weird indentations.
Also consider (not required by this ticket, though) modifying the folder that's exported to so that it is based on `<tenant's-nhsn-org-id>-<date-time-stamp>`. For example: `43242-20240307T095900+0800` where 43242 is the nhsnOrgId in the tenant's config. Again, not required for this ticket, but I think it would be ideal, if it can be squeezed in.

2024-03-08 06:00 UTC, seanmcilvenna requested changes
Sorry... meant to reject to request changes as described in my comment within the code file.

2024-03-11 01:28 UTC, smailliwcs reviewed
One additional general comment: the validation issue `expression`s reflect locations in the "unified bundle" (since that's what we actually perform validation on).  So when we `saveToFolder`, and all those bundled resources get split out into separate files, the `expression`s are no longer accurate.  Not sure how big of a problem this is.

2024-03-11 01:28 UTC, smailliwcs commented on core/src/main/java/com/lantanagroup/link/sender/FileSystemSender.java
> +      else if(resourceType.equals("Patient") && patientIds.stream().anyMatch(p -> p.equals(id))) {
Agreed, and I think even that might be brittle, since we're essentially duplicating the bundle-splitting logic here.  Ideally, that logic (earlier in this method, maybe with the help of some enhancements to the `FhirBundleProcessor`) would produce a `Map` associating each bundle entry index with the filename where the corresponding resource landed during splitting.  Then this annotation code could just parse the index out of the `expression`, read the filename from the `Map`, and set it as the `diagnostics`.

2024-03-11 01:28 UTC, smailliwcs commented on core/src/main/java/com/lantanagroup/link/sender/FileSystemSender.java
> +      String id = expression.substring(expression.indexOf("id = '") + 6, expression.indexOf("')"));
Lots of assumptions here about the structure of the `expression`.  We should be guarding against the possibility of something with no `ofType(...)` or `id = '...'`.  Case in point, if there are no validation issues (or we just haven't run validation yet), `ValidationResultMapper` creates a "No issues found" issue with no `expression`.  That ends up causing a `IndexOutOfBoundsException` here on line 235.

2024-03-11 01:28 UTC, smailliwcs commented on core/src/main/java/com/lantanagroup/link/sender/FileSystemSender.java
>      }
Why only autosave validation results in the split-bundle case?

2024-03-11 01:28 UTC, smailliwcs commented on core/src/main/java/com/lantanagroup/link/sender/FileSystemSender.java
> +        i.setDiagnostics("query-plan.json");
The query plan gets saved as YAML ... we read out the `content[0].data` and save it as `query-plan.yml`.  (Tangent: is it a problem that we lose the FHIR resource representation?)

2024-03-13 01:03 UTC, smailliwcs requested changes

2024-03-13 01:03 UTC, smailliwcs commented on core/src/main/java/com/lantanagroup/link/FhirBundleProcessor.java
> +      int index = this.bundle.getEntry().indexOf(e);
This works, but we've run into performance issues with code like this when processing large bundles, because we're looping over entries (via `indexOf`) _within_ a loop over entries (the containing `for` on line 113).  One resolution would be to change that containing loop to a simple `for (int index = 0; index < bundle.getEntry().size(); index++)` ... then when you need the bundle entry, you can `bundle.getEntry().get(index)` (a constant-time operation), and when you need the index, you already have it.  But whatever the resolution, it should also be applied above wherever we're currently calling `indexOf` within a stream.

2024-03-14 18:16 UTC, smailliwcs approved these changes
Approved, but note the need for one small thread-safety tweak before merging.

2024-03-14 18:55 UTC, seanmcilvenna approved these changes

2024-03-14 19:12 UTC, smailliwcs commented on core/src/main/java/com/lantanagroup/link/FhirHelper.java
> +  public static FHIRPathEngine getFhirPathEngine() {
I don't see any explicit assertion re: thread safety in the documentation for `HapiWorkerContext` and `FHIRPathEngine`.  So safest would be to construct a new instance every time.  That said, before these changes, we were using `FHIRPathEngine` across threads in `ApplyConceptMaps` with no *apparent* ill effects, so maybe it's fine.  Regardless, now that the construction logic has moved here to `FhirHelper`, we should probably move the call in `ApplyConceptMaps` "up" to its `execute` method, so that we're not constructing a new context/engine for every single resource that we apply a concept map to.

2024-03-14 19:46 UTC, ajagann1 commented on core/src/main/java/com/lantanagroup/link/FhirHelper.java
> +  public static FHIRPathEngine getFhirPathEngine() {
Moved the `FHIRPathEngine` variable to the top of the class so it's only initialized once.  Should be good to go here.

2024-03-14 19:58 UTC, smailliwcs commented on core/src/main/java/com/lantanagroup/link/FhirHelper.java
> +  public static FHIRPathEngine getFhirPathEngine() {
Sorry, I need to walk my last comment back.  `ApplyConceptMaps` only used the *validation support* across threads, never the HAPI worker context or the FHIRPath engine.  And I think that only worked because we made sure to `fetchAllStructureDefinitions` in the constructor.  So I think we need to revert this last commit.  Yes, we'll be constructing a new context/engine on every concept map application, but that's the way `ApplyConceptMaps` did it before this PR, so apparently it wasn't a huge performance concern.

2024-03-14 20:33 UTC, merged