LNK-2187 Refactor MVP tenant and report summaries
lantanagroup/link pull request #723
Opened 2024-03-14 14:23 UTC by seanmcilvenna

* Facilities in UI only displays a single line per facility, not a separate line/row per report
* Activities in UI only shows the number of patients (in-ip out of total).
* Changed ApiConfig to capture short/long name for each measure def - the api config will need to be udpated when deployed
* Removed IntelliJ run config from git so that it would stop trying to commit my changes to the run configs

2024-03-14 20:51 UTC, smailliwcs requested changes

2024-03-14 20:51 UTC, smailliwcs commented on core/src/main/resources/get-reports.sql
This produces duplicate records in the multi-measure use case (one for each additional measure evaluated).  Recommend replacing with (something like) the following:

```sql
SELECT
	dbo.report.id,
	version,
	status,
	generatedTime,
	submittedTime,
	periodStart,
	periodEnd,
	measureIds,
	totalPatients,
	maxTotalInIP
FROM dbo.report
INNER JOIN (
	SELECT
		R.id,
		MAX(PL.patientCount) AS totalPatients,
		MAX(A.ipPatientCount) AS maxTotalInIP
	FROM dbo.report AS R
	INNER JOIN dbo.reportPatientList AS RPL ON R.id = RPL.reportId
	INNER JOIN (
		SELECT *, (SELECT COUNT(*) FROM OPENJSON(patients)) AS patientCount
		FROM dbo.patientList
	) AS PL ON RPL.patientListId = PL.id
	INNER JOIN (
		SELECT *, (SELECT COUNT(*) FROM OPENJSON(report, '$.contained[0].entry')) AS ipPatientCount
		FROM dbo.[aggregate]
	) AS A ON R.id = A.reportId
	GROUP BY R.id
) AS counts ON dbo.report.id = counts.id;
```

2024-03-14 21:08 UTC, seanmcilvenna commented on core/src/main/java/com/lantanagroup/link/db/SharedService.java
> +              .stream()
Love this. I always forget about `.flatMap()`. Thanks!

2024-03-14 21:08 UTC, seanmcilvenna commented on core/src/main/java/com/lantanagroup/link/db/SharedService.java
> +    }
Also love it

2024-03-14 21:16 UTC, seanmcilvenna commented on core/src/main/java/com/lantanagroup/link/db/SharedService.java
> +                        .orElse(null);
I thought about this for a minute...
I like the idea of "id" being a property in MeasureDefConfig, though... in case we ever have a desire to pass around `MeasureDefConfig`. And if I were to convert it to a Map and keep the "id" property in the `MeasureDefConfig`, then the YAML would like this:
```yaml
  measure-definitions:
    NHSNGlycemicControlHypoglycemicInitialPopulation:
      id: NHSNGlycemicControlHypoglycemicInitialPopulation
      short-name: Hypo
      long-name: Hypoglycemia
      definition-url: 'https://ehr-test.nhsnlink.org/fhir/Bundle/NHSNGlycemicControlHypoglycemicInitialPopulation'
```
I'm not terribly fond of the duplication there... Am I thinking wrong?

2024-03-14 21:20 UTC, seanmcilvenna commented on core/src/main/java/com/lantanagroup/link/db/SharedService.java
> +                      tenantConfig.getCdcOrgId().toLowerCase().contains(searchCriteria.toLowerCase());
Changing... but, fyi, using `StringUtils.containsIgnoreCase`

2024-03-15 00:57 UTC, smailliwcs commented on core/src/main/java/com/lantanagroup/link/db/SharedService.java
> +                        .orElse(null);
Agreed, let's not require duplication in the YAML.  Instead of changing back to a `Map`, what about a helper in `ApiConfig` that deduplicates the ID-based lookup logic?  Something like `MeasureDefConfig getMeasureDefinition(String measureId)`?

2024-03-15 02:22 UTC, seanmcilvenna commented on core/src/main/java/com/lantanagroup/link/db/SharedService.java
> +                        .orElse(null);
Good idea. Done! ✔️

2024-03-15 18:20 UTC, merged