Lnk 2116 logging improvements
lantanagroup/link pull request #744
Opened 2024-04-10 22:05 UTC by edward-miller-lcg

2024-04-11 03:29 UTC, seanmcilvenna approved these changes
Generally looks good. Would like to know if the reportId gets populated into `logging_event_property` table (or whatever it's called)... Ultimately would like to be able to perform the following select, if at all possible:
`SELECT * FROM logging_event e JOIN logging_event_property p ... WHERE p.name = 'reportId' and p.value = '12345'`

2024-04-11 13:54 UTC, smailliwcs requested changes

2024-04-11 13:54 UTC, smailliwcs commented on api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java
> +    MDC.clear();
Need to put this in a `finally`, where everything below the `MDC.put` above forms the body of the corresponding `try`.

2024-04-11 14:36 UTC, edward-miller-lcg commented on api/src/main/java/com/lantanagroup/link/api/ReportGenerator.java
> +                MDC.setContextMap(contextMapCopy);
Is it that you want to tag the report Id there?

2024-04-11 14:37 UTC, edward-miller-lcg commented on api/src/main/java/com/lantanagroup/link/api/controller/ReportController.java
> +        logger.info("Skipping initial query and store", report.getId());
ah, I meant to remove this. I was testing the logback funtionality and wanted to see how DBAppender reacted to an arg with no placeholder in the string. I'll work to remove it.

2024-04-11 14:40 UTC, edward-miller-lcg commented on api/src/main/resources/logback.xml
> +    <logger name="com.lantanagroup.link" level="INFO" />
I can roll back this change.

2024-04-12 14:58 UTC, smailliwcs approved these changes

2024-05-04 20:00 UTC, merged